### ISSUE TITLE
dnsu2t error

### ISSUE THREAD

**Issue by kosiun** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#22]
CONNECTED SUCCESSFULLY 

```
---Tunneling  starts-----
file parsing error at line 35: unknown section <dnsu2t>
 KILLING PROCESS....
 DONE 
```

Hello, how do I fix this, I've tried but it doesn't work.

**Comment by kosiun** [comment]
> CONNECTED SUCCESSFULLY
> 
> ```
> ---Tunneling  starts-----
> file parsing error at line 35: unknown section <dnsu2t>
>  KILLING PROCESS....
>  DONE 
> ```
> 
> Hello, how do I fix this, I've tried but it doesn't work.
it was resolved by deleting dnsu2t and dnstc I used openwrt, then how do I bridge the interface from abdoxfox/http-ssl-ssh-injector with interface eth0

**Comment by Erwingwapo999** [comment]
I think its not yet for openwrt maybe soon,
Did you solved your problem now!
