### ISSUE TITLE
issues for connection

### ISSUE THREAD

**Issue by meysamrn** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#36]
error :
Authenticate to password
Port used by another programs 
CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
./proxification: 30: redsocksv: not found
[+] KILLING PROCESS....
sudo: python: command not found
[+] DONE

**Comment by abdoxfox** [comment]
Make sure all required depencies and try again from scratch

**Comment by meysamrn** [comment]
the problem is the package openssh not find error appearing whlie install required depencies
