### ISSUE TITLE
Me lanza solo este error que estoy haciendo mal ayuda por favor

### ISSUE THREAD

**Issue by Vycanis09** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#38]
/---logs----
Connecting Using Direct SSH
Failed to connect ... Try again                         [+] KILLING PROCESS....
[+] DONE                                                ---logs----
Connecting Using Direct SSH
Failed to connect ... Try again
[+] KILLING PROCESS....
[+] DONE
---logs----
![Screenshot_2023-08-31-10-23-12-800_com termux](https://github.com/abdoxfox/HTTP-CUSTOM-HEADERS-VPN/assets/104798178/9d438190-548d-40f4-b19e-a0e6700bc4c2)

**Comment by abdoxfox** [comment]
i need some extra info about your issue nothing clear in this screenshoot

**Comment by Vycanis09** [comment]
![Screenshot_2023-08-31-10-58-17-532_com termux](https://github.com/abdoxfox/HTTP-CUSTOM-HEADERS-VPN/assets/104798178/a0a367cb-a869-46e3-a8eb-38b27751e446)
