### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Vycanis09** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#39]
When I activate it in termux and the connection starts, the wifi sharing is not activated for me, I activate it and it is constantly deactivated because that happens, any solution????

**Comment by abdoxfox** [comment]
A fixing update was uploaded.
Try it and reply me

**Comment by Vycanis09** [comment]
I already updated it and nothing keeps turning off wifi sharing when starting the tunnel
