### ISSUE TITLE
even if ssh is valid, it doesnt connect.

### ISSUE THREAD

**Issue by evoziosk** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#42]
I am on arch linux and I believe i have all the dependencies installed. Still it doesnt connect, just says connection closed in a loop

**Comment by abdoxfox** [comment]
it seems that something wrong in settings file

**Comment by cjayacopra** [comment]
I got the same issue here. the settings i have put is working in http custom for android. but is not working with this on my linux machine

**Comment by LilBtr** [comment]
same problem

**Comment by cjayacopra** [comment]
Are you guys perhaps using websocket? I'm using websocket and realized that the codes does not support websocket.

**Comment by hasaranga** [comment]
Same here on debian 11

**Comment by abdoxfox** [comment]
> Are you guys perhaps using websocket? I'm using websocket and realized that the codes does not support websocket.

Paste your settings maybe you did something wrong 
About websocket is working fine .

**Comment by cjayacopra** [comment]
> > Are you guys perhaps using websocket? I'm using websocket and realized that the codes does not support websocket.
> 
> Paste your settings maybe you did something wrong About websocket is working fine .

On libernet in openwrt and http custom in android the setup is like this, Direct SSH+Payload+WS.

It's working perfectly fine but not in this program. I hope you can help me to work this in your program for my Linux machine

**Comment by abdoxfox** [comment]
Show logs or settings to figure out what's your issues is

**Comment by cjayacopra** [comment]
> Show logs or settings to figure out what's your issues is

May you please share where can I get the logs? There is no log file when using the program. It's just in loop saying not connected

**Comment by cjayacopra** [comment]
![Uploading Screenshot_20240406-023732_Termux.png…]()
