### ISSUE TITLE
No conecta nada

### ISSUE THREAD

**Issue by Vycanis09** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#44]
Instale todo lo que se necesita configure bn mi archivo y solo se queda en conexión closed todo el tiempo que puede estar mal

**Comment by abdoxfox** [comment]
Hello , can you describe your issue and show logs for help you

**Comment by Vycanis09** [comment]
Cuando le doy en conectar solo me aparece conección closed y así se repite y vuelve a lo mismo

**Comment by Vycanis09** [comment]
![Screenshot_20240412-131949](https://github.com/abdoxfox/HTTP-CUSTOM-HEADERS-VPN/assets/104798178/23008a75-fad3-4248-bd22-847b75053892)

**Comment by abdoxfox** [comment]
Make sure that all required packages are installed also python module : certifi

**Comment by Vycanis09** [comment]
Ya revise todo y está instalado todo pero sigue lo mismo

**Comment by Vycanis09** [comment]
\033[1;32m ++++ LOGS ++++\033[0m                ^CTraceback (most recent call last):              File "/data/data/com.termux/files/home/HTTP-CUSTOM-HEADERS-VPN/src/ssh.py", line 7, in <module>                                                   import configparser                           File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                              File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1049, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data

**Comment by abdoxfox** [comment]
Contact me in telegram 
https://t.me/Abdoxfox_official
